// Persistent CLI config — lives at ./papervault.config.json by default.
// Generated by `papervault init`; consumed by `papervault backup` so users
// don't have to re-type flags every run.
//
// Schema is intentionally tiny — only the things that don't change between
// invocations. Secret values are NEVER stored here.

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

export const CONFIG_FILENAME = 'papervault.config.json';
export const CONFIG_VERSION = '1';

/**
 * @typedef {object} PapervaultConfig
 * @property {string} version
 * @property {string} source           Source URI (file://, stdin, azure-kv://, etc.)
 * @property {number} threshold
 * @property {number} shares
 * @property {string} [vaultName]
 * @property {string[]} [custodianNames]
 * @property {string} [savePath]       Absolute dir; backup will write <savePath>/vault-<id>/
 * @property {string} [select]
 * @property {number} [maxSecrets]
 */

export function configPath(cwd = process.cwd()) {
    return resolve(cwd, CONFIG_FILENAME);
}

export function configExists(cwd = process.cwd()) {
    return existsSync(configPath(cwd));
}

/** @returns {Promise<PapervaultConfig|null>} */
export async function readConfig(cwd = process.cwd()) {
    const p = configPath(cwd);
    if (!existsSync(p)) return null;
    let raw;
    try { raw = await readFile(p, 'utf8'); }
    catch (err) { throw new Error(`could not read ${p}: ${err.message}`); }
    let doc;
    try { doc = JSON.parse(raw); }
    catch (err) { throw new Error(`invalid JSON in ${p}: ${err.message}`); }
    if (doc.version !== CONFIG_VERSION) {
        throw new Error(`${p} has version ${doc.version}; this CLI expects ${CONFIG_VERSION}.`);
    }
    return doc;
}

/** @param {PapervaultConfig} cfg */
export async function writeConfig(cfg, cwd = process.cwd()) {
    const p = configPath(cwd);
    // Sort keys for deterministic diffs.
    const ordered = {
        version: CONFIG_VERSION,
        source: cfg.source,
        threshold: cfg.threshold,
        shares: cfg.shares,
        ...(cfg.vaultName != null      ? { vaultName: cfg.vaultName }           : {}),
        ...(cfg.custodianNames != null ? { custodianNames: cfg.custodianNames } : {}),
        ...(cfg.savePath != null       ? { savePath: cfg.savePath }             : {}),
        ...(cfg.select != null         ? { select: cfg.select }                 : {}),
        ...(cfg.maxSecrets != null     ? { maxSecrets: cfg.maxSecrets }         : {}),
    };
    await writeFile(p, JSON.stringify(ordered, null, 2) + '\n', 'utf8');
    return p;
}
